### PR TITLE
Feature: Use postgres version 12

### PR DESCRIPTION
**Pull request by bohme**
Asana-task: [Upgrade Postgres to version 12](https://app.asana.com/0/1142794766483633/1189223519290417/f)

### CODE REVIEW

**Review by runephilosof-abtion — CHANGES_REQUESTED** [review]
Also update `README.example.md`

**Comment by runephilosof-abtion** [comment]
The Heroku resource for also needs to be updated https://dashboard.heroku.com/apps/muffi-template/resources

**Comment by jeppester** [comment]
@runephilosof-abtion Please review again

**Review by runephilosof-abtion — APPROVED** [review]
Yay

**Comment by prrrnd** [comment]
sweet!

**Pull request merged**
