### PR TITLE
Update babel config js to avoid warnings

### PR DESCRIPTION
**Pull request by runephilosof-abtion**
Dependent on #486 so merge that one first.

### CODE REVIEW

**Review by jeppester — APPROVED** [review]
:+1:

**Comment by jeppester** [comment]
@runephilosof-abtion I've merged #486 can I rebase and merge this?

**Comment by runephilosof-abtion** [comment]
Squashing is so annoying. If it had been merged normally, the rebase would not have given a conflict.

**Comment by jeppester** [comment]
> Squashing is so annoying. If it had been merged normally, the rebase would not have given a conflict.

I'm with you on that.

However; squashing is more forgiving and does not require as well-structured commits as rebasing. It lowers the git skill requirements slightly.

**Comment by runephilosof-abtion** [comment]
> > Squashing is so annoying. If it had been merged normally, the rebase would not have given a conflict.
> 
> I'm with you on that.
> 
> However; squashing is more forgiving and does not require as well-structured commits as rebasing.

I guess what I want is for Github to fast forward if there is already only one commit and it is already at the tip of the base branch.

**Pull request merged**
