### PR TITLE
CI: Update postgres to 14.6

### PR DESCRIPTION
**Pull request by runephilosof-abtion**
This is the default version used on Heroku currently

### CODE REVIEW

**Review by jeppester — APPROVED** [review]
:+1:

**Comment by jeppester** [comment]
We forgot to update the version in `app.json`. I'm going to do that directly on main.

I just got the `app.json` file in a working state again. It would be a shame for it to already become outdated!

**Comment by jeppester** [comment]
And we also forgot the docker compose file. Updating that as well

**Comment by jeppester** [comment]
Done

**Comment by runephilosof-abtion** [comment]
I am adding 1SLA` label to this one, even though each project should of course match their production version

**Pull request merged**
