### PR TITLE
Feature: Add empty spec files to please SimpleCov

### PR DESCRIPTION
**Pull request by bohme**
Adding empty files to test empty files.

Hunting those 100% 🤠

### CODE REVIEW

**Comment by GeoffAbtion** [comment]
Better solution, delete the empty files.

**Comment by bohme** [comment]
We could do my favourite rails thingy and split the `rails` gem into it's components :P

**Comment by runephilosof-abtion** [comment]
> Better solution, delete the empty files.

ActionCable could be deleted, since a lot of projects don't use it.
But jobs and mailers are typically used, we would want projects to inherit from ApplicationMailer as is Rails default.

**Comment by GeoffAbtion** [comment]
> But jobs and mailers are typically used, we would want projects to inherit from ApplicationMailer as is Rails default.

At which point we could create the needed files.

**Comment by GeoffAbtion** [comment]
We should either keep all of them or none of them, but either way there should be test files for the existing files.

I vote we merge this PR and we can argue about deleting things in a separate PR.

**Pull request merged**
