### PR TITLE
Feature: Don't run seeds in release phase

### PR DESCRIPTION
**Pull request by bohme**
Asana-task: [Fraxx: Don't seed in the release phase action](https://app.asana.com/0/1142794766483633/1188627776772507/f)

### CODE REVIEW

**Review by prrrnd — APPROVED** [review]

**Comment by prrrnd** [comment]
(shouldn't there be a worker as well for sidekiq?)

**Comment by bohme** [comment]
(first after we have added sidekiq to this project)

**Comment by jeppester** [comment]
Won't this change cause the review apps to have their DBs seeded?

If so I think we should also add a review app script that does the seeding.

**Review by hcarreras — APPROVED** [review]

**Review by jeppester — CHANGES_REQUESTED** [review]
As stated in my comment above we should still seed review apps

**Comment by bohme** [comment]
I agree, that's why I added this commit: https://github.com/abtion/muffi/pull/94/commits/1a6c553d023e980840d3407d5946c3a6915e9c4e

**Comment by jeppester** [comment]
Oh, I didn't notice that. I'll recreate the review app and see if it works as intended, then lets merge if it does :-)

**Comment by jeppester** [comment]
It didn't work as intended :disappointed:
The postdeploy script did not appear to run at all

**Comment by bohme** [comment]
yea looks like stuff blew up... I suspect it to be the `schema:load` part 🤷‍♀️

**Comment by jeppester** [comment]
It appears to be working now :+1:, I'll rebuild the review app once more to do one final check.
It worries me that I can't seem to find a log of the postdeploy script in heroku's UI. Maybe I'm not good at looking for it? :thinking:

**Comment by jeppester** [comment]
The seed user magically appears shortly after the release script is finished running. So it works :-)

**Comment by bohme** [comment]
does this work?
https://help.heroku.com/LXRRBMM3/how-do-i-view-postdeploy-script-output#:~:text=This%20output%20is%20available%20via,View%20initial%20app%20setup%22%20option.

**Review by jeppester — APPROVED** [review]

**Pull request merged**
