### PR TITLE
bin/setup: Create .env.development if it does not exist.

### PR DESCRIPTION
**Pull request by GeoffAbtion**
If the .env.development file does not exist, create it based on the
.env.development.example file.
If already exists, do nothing.

This allows an app to be setup from git clone to passing tests by a single: `bin/setup` command.

### CODE REVIEW

**Comment by GeoffAbtion** [comment]
I agree that that would be a better way of handling environment variables. 👍

**Comment by jeppester** [comment]
> I prefer to not use `.example`.
> Instead track `.env` and `.env.development` in Git.
> Then it is even easier to get running locally, also it is the documented way of doing it in the `dotenv` gem => the expected way
> 
> Instead rename `.env.development.example` to `.env.development`.
> If developers need local changes to the development env variables, they can create `.env.development.local`
> Remove `.env.development` and `.env` from `.gitignore`.
> Add `.env.*.local` to `.gitignore`

This should be a simple change, lets get it done!

**Comment by jeppester** [comment]
I'm closing this in favor of @runephilosof-abtion's solution, I'll make a PR for it.

**Comment by GeoffAbtion** [comment]
Great, thanks @jeppester 👍

**Pull request closed without merging**
