### PR TITLE
Remove deprecation warnings from Ruby 2.7 when running rspec

### PR DESCRIPTION
**Pull request by prrrnd**

### CODE REVIEW

**Review by jeppester — CHANGES_REQUESTED** [review]
There are still a few warnings in the rspec output:
```
/home/runner/work/muffi/muffi/vendor/bundle/ruby/2.7.0/gems/faker-2.7.0/lib/faker.rb:158: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/runner/work/muffi/muffi/vendor/bundle/ruby/2.7.0/gems/i18n-1.7.1/lib/i18n.rb:195: warning: The called method `translate' is defined here

/home/runner/work/muffi/muffi/vendor/bundle/ruby/2.7.0/gems/selenium-webdriver-3.142.6/lib/selenium/webdriver/chrome/driver.rb:43: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/runner/work/muffi/muffi/vendor/bundle/ruby/2.7.0/gems/selenium-webdriver-3.142.6/lib/selenium/webdriver/remote/bridge.rb:44: warning: The called method `handshake' is defined here

/home/runner/work/muffi/muffi/vendor/bundle/ruby/2.7.0/gems/selenium-webdriver-3.142.6/lib/selenium/webdriver/remote/bridge.rb:62: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/runner/work/muffi/muffi/vendor/bundle/ruby/2.7.0/gems/selenium-webdriver-3.142.6/lib/selenium/webdriver/remote/w3c/bridge.rb:35: warning: The called method `initialize' is defined here

```

**Comment by runephilosof-abtion** [comment]
@jeppester A quick search turned up no reported issues in those gems regarding keyword parameters. So maybe we are using them in the wrong way.

**Comment by runephilosof-abtion** [comment]
The latest gem updates in main seems to have cleared the warnings.

**Comment by jeppester** [comment]
> The latest gem updates in main seems to have cleared the warnings.

Great! :+1:

**Pull request closed without merging**
